### ISSUE TITLE
click_quiz - ERROR random.choice(choices).click()

### ISSUE THREAD

**Issue by velotoxicsounds** [velotoxicsounds/Microsoft-Rewards-Bot#6]
2020-11-09 00:26:18,579 :: INFO :: root :: Number of open offers: 5
2020-11-09 00:26:43,645 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\ms_rewards.py", line 1018, in <module>
    iter_dailies()
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\ms_rewards.py", line 667, in iter_dailies
    click_quiz()
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\ms_rewards.py", line 745, in click_quiz
    random.choice(choices).click()
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\env\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\env\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\velot\OneDrive\ROOT-VERZEICHNIS\SAMMLUNG-COMPUTER\GITHUB\VISUALSTUDIO\Microsoft-Rewards-Bot\env\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=86.0.4240.183)
  (Driver info: chromedriver=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}),platform=Windows NT 10.0.18363 x86_64)

**Comment by velotoxicsounds** [comment]
Re-insert Time Sleep - Next TO-Do

**Comment by velotoxicsounds** [comment]
The project will no longer be supported. Microsoft has found a new anti-bot measure and detected all my accounts. Closed
